import numpy as np
import time

def write_cube(filename, symbols, coords, origin, spacing, N, density):
    """Writes a standard Gaussian .cube file for 3D visualization."""
    # Dictionary mapping atomic symbols to atomic numbers
    elements = {'H':1, 'HE':2, 'LI':3, 'BE':4, 'B':5, 'C':6, 'N':7, 'O':8, 'F':9, 'NE':10,
                'SI':14, 'P':15, 'S':16, 'CL':17, 'AR':18, 'K':19, 'CA':20, 'BR':35, 
                'I':53, 'CS':55, 'PB':82}
    
    ANG_TO_BOHR = 1.8897259886
    Z = [elements.get(s.upper(), 0) for s in symbols]
    coords_bohr = coords * ANG_TO_BOHR

    with open(filename, 'w') as f:
        f.write("miniBSE Exciton Transition Density\n")
        f.write("Generated by ExcitonCube Module\n")
        # Format: N_atoms, Origin X, Y, Z
        f.write(f"{len(symbols):5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")
        # Format: N_points_X, Spacing_X, 0, 0
        f.write(f"{N[0]:5d} {spacing:12.6f} 0.000000 0.000000\n")
        f.write(f"{N[1]:5d} 0.000000 {spacing:12.6f} 0.000000\n")
        f.write(f"{N[2]:5d} 0.000000 0.000000 {spacing:12.6f}\n")
        
        # Write atom coordinates
        for i in range(len(symbols)):
            f.write(f"{Z[i]:5d} {float(Z[i]):12.6f} {coords_bohr[i,0]:12.6f} {coords_bohr[i,1]:12.6f} {coords_bohr[i,2]:12.6f}\n")
        
        # Cube files require Z to vary fastest
        dens_3d = density.reshape((N[0], N[1], N[2]))
        for ix in range(N[0]):
            for iy in range(N[1]):
                for iz in range(N[2]):
                    f.write(f"{dens_3d[ix, iy, iz]:13.5E} ")
                    if iz % 6 == 5:
                        f.write("\n")
                f.write("\n")

def generate_exciton_cubes(solver, bse_vec, shells, symbols, coords, prefix, spacing_ang=0.5, margin_ang=3.5, nthreads=4):
    """
    Evaluates MOs on a 3D grid in chunks to save memory, 
    and writes the resulting hole and electron densities to .cube files.
    """
    import libint_cpp
    ANG_TO_BOHR = 1.8897259886
    
    print(f"\n  [Cube] Initializing 3D Grid (spacing: {spacing_ang} Å, margin: {margin_ang} Å)...")
    mins = np.min(coords, axis=0) - margin_ang
    maxs = np.max(coords, axis=0) + margin_ang
    
    # Calculate number of grid points in each dimension
    Nx = int(np.ceil((maxs[0] - mins[0]) / spacing_ang))
    Ny = int(np.ceil((maxs[1] - mins[1]) / spacing_ang))
    Nz = int(np.ceil((maxs[2] - mins[2]) / spacing_ang))
    
    xs = np.linspace(mins[0], mins[0] + Nx*spacing_ang, Nx, endpoint=False)
    ys = np.linspace(mins[1], mins[1] + Ny*spacing_ang, Ny, endpoint=False)
    zs = np.linspace(mins[2], mins[2] + Nz*spacing_ang, Nz, endpoint=False)
    
    # Meshgrid 'ij' ensures coordinates align with cube file layout
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing='ij')
    grid_points_ang = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T
    grid_points_bohr = grid_points_ang * ANG_TO_BOHR
    n_points = len(grid_points_bohr)
    
    print(f"  [Cube] Grid size: {Nx} x {Ny} x {Nz} = {n_points} points.")
    
    # Pre-calculate MO weights for the exciton
    n_occ_tot = solver.C.shape[1] - solver.n_virt
    C_occ = solver.C[:, :n_occ_tot]
    C_virt = solver.C[:, n_occ_tot:]
    
    weights = bse_vec**2
    hole_weights = np.zeros(n_occ_tot)
    elec_weights = np.zeros(solver.n_virt)
    
    for idx, w in enumerate(weights):
        i_rel = solver.ham.valid_i[idx]
        a_rel = solver.ham.valid_a[idx]
        i_abs = (solver.homo_index - solver.n_occ + 1) + i_rel
        hole_weights[i_abs] += w
        elec_weights[a_rel] += w

    rho_h = np.zeros(n_points)
    rho_e = np.zeros(n_points)

    # -----------------------------------------------------------------
    # --- MASSIVE OPTIMIZATION: Filter out orbitals with zero weight --
    # -----------------------------------------------------------------
    threshold = 1e-6
    active_holes = np.where(hole_weights > threshold)[0]
    active_elecs = np.where(elec_weights > threshold)[0]
    
    C_occ_active = C_occ[:, active_holes]
    hole_weights_active = hole_weights[active_holes]
    
    C_virt_active = C_virt[:, active_elecs]
    elec_weights_active = elec_weights[active_elecs]
    
    print(f"  [Cube] Optimization: Reduced Hole MOs from {len(hole_weights)} to {len(active_holes)}")
    print(f"  [Cube] Optimization: Reduced Elec MOs from {len(elec_weights)} to {len(active_elecs)}")
    
    # NEW: Combine them so C++ only has to evaluate the Gaussians ONCE per chunk
    C_combined = np.ascontiguousarray(np.hstack([C_occ_active, C_virt_active]))
    n_active_holes = len(active_holes)
    # -----------------------------------------------------------------

    # CHUNK LOGIC: Prevent RAM explosion
    chunk_size = 10000 
    n_chunks = int(np.ceil(n_points / chunk_size))
    print(f"  [Cube] Evaluating grid in {n_chunks} chunks via C++ acceleration...")
    
    t0 = time.time()
    
    for c_idx, i in enumerate(range(0, n_points, chunk_size)):
        chunk_pts = grid_points_bohr[i : i+chunk_size]
        
        # ONE C++ call: Returns tiny (10000 x ~90) array instead of a massive (10000 x 15000) array
        psi_chunk = libint_cpp.evaluate_mos_on_grid(shells, C_combined, chunk_pts, nthreads)
        
        # Split the returned matrix back into holes and electrons
        psi_occ_chunk = psi_chunk[:, :n_active_holes]
        psi_virt_chunk = psi_chunk[:, n_active_holes:]
        
        # Final accumulation
        rho_h[i : i+chunk_size] = np.sum((psi_occ_chunk**2) * hole_weights_active, axis=1)
        rho_e[i : i+chunk_size] = np.sum((psi_virt_chunk**2) * elec_weights_active, axis=1)
        
        # Print a progress update every 10%
        if c_idx > 0 and c_idx % max(1, n_chunks // 10) == 0:
            elapsed = time.time() - t0
            pct = (c_idx / n_chunks) * 100
            print(f"    ... {pct:4.1f}% complete ({c_idx}/{n_chunks} chunks) in {elapsed:.1f}s")

    origin_bohr = np.array([xs[0], ys[0], zs[0]]) * ANG_TO_BOHR
    spacing_bohr = spacing_ang * ANG_TO_BOHR

    rho_diff = rho_e - rho_h
    
    print(f"  [Cube] Writing {prefix}_hole.cube ...")
    write_cube(f"{prefix}_hole.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx, Ny, Nz), rho_h)
    
    print(f"  [Cube] Writing {prefix}_elec.cube ...")
    write_cube(f"{prefix}_elec.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx, Ny, Nz), rho_e)

    # Write the combined difference file
    print(f"  [Cube] Writing {prefix}_diff.cube (Electron = Positive, Hole = Negative)...")
    write_cube(f"{prefix}_diff.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx, Ny, Nz), rho_diff)

