import numpy as np
import time

# Try to import the new C++ function, fail gracefully if it's not compiled yet
try:
    from libint_cpp import write_cube_data
    HAS_CPP_WRITER = True
except ImportError:
    HAS_CPP_WRITER = False

def write_cube(filename, symbols, coords, origin, spacing, N, density, use_cpp=True):
    """Writes a standard Gaussian .cube file for 3D visualization."""
    start_time = time.perf_counter()
    
    # Dictionary mapping atomic symbols to atomic numbers
    elements = {'H':1, 'HE':2, 'LI':3, 'BE':4, 'B':5, 'C':6, 'N':7, 'O':8, 'F':9, 'NE':10, 'AL':13, 
                'SI':14, 'P':15, 'S':16, 'CL':17, 'AR':18, 'K':19, 'CA':20, 'ZN':30, 'GA':31, 'AS':33, 'SE':34, 'BR':35,
                'CD':48, 'IN':49, 'SB':51, 'TE':52, 'I':53, 'CS':55, 'HG':80, 'PB':82, 'BI':83}
    
    ANG_TO_BOHR = 1.8897259886
    Z = [elements.get(s.upper(), 0) for s in symbols]
    coords_bohr = coords * ANG_TO_BOHR

    # Cube files require Z to vary fastest
    dens_3d = density.reshape((N[0], N[1], N[2]))

    # Step 1: Write the header using Python (mode 'w' creates/overwrites the file)
    with open(filename, 'w') as f:
        f.write("miniBSE Exciton Transition Density\n")
        f.write("Generated by ExcitonCube Module\n")
        # Format: N_atoms, Origin X, Y, Z
        f.write(f"{len(symbols):5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")
        # Format: N_points_X, Spacing_X, 0, 0
        f.write(f"{N[0]:5d} {spacing:12.6f} 0.000000 0.000000\n")
        f.write(f"{N[1]:5d} 0.000000 {spacing:12.6f} 0.000000\n")
        f.write(f"{N[2]:5d} 0.000000 0.000000 {spacing:12.6f}\n")
        
        # Write atom coordinates
        for i in range(len(symbols)):
            f.write(f"{Z[i]:5d} {float(Z[i]):12.6f} {coords_bohr[i,0]:12.6f} {coords_bohr[i,1]:12.6f} {coords_bohr[i,2]:12.6f}\n")
    
    header_time = time.perf_counter()
    
    # Step 2: Append the heavy 3D grid data
    if use_cpp and HAS_CPP_WRITER:
        # Fast C++ writer (opens in 'a' mode under the hood)
        write_cube_data(filename, dens_3d)
        mode_used = "C++"
    else:
        # Fallback to pure Python (re-open in 'a' mode)
        with open(filename, 'a') as f:
            for ix in range(N[0]):
                for iy in range(N[1]):
                    for iz in range(N[2]):
                        f.write(f"{dens_3d[ix, iy, iz]:13.5E} ")
                        if iz % 6 == 5:
                            f.write("\n")
                    f.write("\n")
        mode_used = "Python"

    end_time = time.perf_counter()
    total_time = end_time - start_time
    append_time = end_time - header_time
    print(f"  [Cube] Exported {filename} ({mode_used}): Total {total_time:.3f}s (Data {append_time:.3f}s)")

def generate_cubes(solver, bse_states_dict, mo_list, spinor_list, soc_U, shells, symbols, coords, spacing_ang=0.5, margin_ang=3.5, nthreads=4, use_cpp=True):
    import libint_cpp
    ANG_TO_BOHR = 1.8897259886
    
    print(f"\n  [Cube] Initializing 3D Grid (spacing: {spacing_ang} Å, margin: {margin_ang} Å)...")
    mins = np.min(coords, axis=0) - margin_ang
    maxs = np.max(coords, axis=0) + margin_ang
    
    Nx = int(np.ceil((maxs[0] - mins[0]) / spacing_ang))
    Ny = int(np.ceil((maxs[1] - mins[1]) / spacing_ang))
    Nz = int(np.ceil((maxs[2] - mins[2]) / spacing_ang))
    
    xs = np.linspace(mins[0], mins[0] + Nx*spacing_ang, Nx, endpoint=False)
    ys = np.linspace(mins[1], mins[1] + Ny*spacing_ang, Ny, endpoint=False)
    zs = np.linspace(mins[2], mins[2] + Nz*spacing_ang, Nz, endpoint=False)
    
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing='ij')
    grid_points_bohr = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T * ANG_TO_BOHR
    n_points = len(grid_points_bohr)
    
    print(f"  [Cube] Grid size: {Nx} x {Ny} x {Nz} = {n_points} points.")
    
    n_spatial_total = solver.C.shape[1]
    active_mos = set()
    
    # --- 1. Identify Active MOs from Pure Spatial Requests ---
    for mo in mo_list:
        active_mos.add(mo)
        
    # --- 2. Identify Active MOs from Spinor Requests ---
    if spinor_list and soc_U is not None:
        n_mo_act = soc_U.shape[0] // 2
        offset = solver.homo_index - solver.n_occ + 1
        for sp_idx in spinor_list:
            U_a = soc_U[:n_mo_act, sp_idx]
            U_b = soc_U[n_mo_act:, sp_idx]
            weights = np.abs(U_a)**2 + np.abs(U_b)**2
            for p_rel, w in enumerate(weights):
                if w > 1e-6:
                    active_mos.add(offset + p_rel)
                    
    # --- 3. Identify Active MOs from BSE Excitons ---
    bse_abs_holes = {p: np.zeros(n_spatial_total) for p in bse_states_dict}
    bse_abs_elecs = {p: np.zeros(n_spatial_total) for p in bse_states_dict}
    
    for prefix, bse_vec in bse_states_dict.items():
        weights = bse_vec**2
        for idx, w in enumerate(weights):
            if w > 1e-6:
                i_rel = solver.ham.valid_i[idx]
                a_rel = solver.ham.valid_a[idx]
                i_abs = (solver.homo_index - solver.n_occ + 1) + i_rel
                a_abs = (solver.homo_index + 1) + a_rel
                
                bse_abs_holes[prefix][i_abs] += w
                bse_abs_elecs[prefix][a_abs] += w
                active_mos.add(i_abs)
                active_mos.add(a_abs)

    active_mos = sorted(list(active_mos))
    mo_to_col = {mo: col for col, mo in enumerate(active_mos)}
    
    print(f"  [Cube] Union of Active Spatial MOs: {len(active_mos)}")
    C_active = np.ascontiguousarray(solver.C[:, active_mos])
    
    # Initialize Density Arrays
    rho_mo = {mo: np.zeros(n_points) for mo in mo_list}
    rho_sp = {sp: np.zeros(n_points) for sp in spinor_list}
    rho_bse_h = {p: np.zeros(n_points) for p in bse_states_dict}
    rho_bse_e = {p: np.zeros(n_points) for p in bse_states_dict}
    
    chunk_size = 10000 
    n_chunks = int(np.ceil(n_points / chunk_size))
    print(f"  [Cube] Evaluating grid in {n_chunks} chunks via C++ acceleration...")
    
    t0 = time.time()
    for c_idx, i in enumerate(range(0, n_points, chunk_size)):
        chunk_pts = grid_points_bohr[i : i+chunk_size]
        # One pass evaluation!
        psi_chunk = libint_cpp.evaluate_mos_on_grid(shells, C_active, chunk_pts, nthreads)
        
        # Build Spatial MOs (Signed Wavefunctions)
        for mo in mo_list:
            rho_mo[mo][i : i+chunk_size] = psi_chunk[:, mo_to_col[mo]]
            
        # Build Spinor Densities (|Psi|^2)
        if spinor_list and soc_U is not None:
            n_mo_act = soc_U.shape[0] // 2
            offset = solver.homo_index - solver.n_occ + 1
            for sp in spinor_list:
                U_a_full = soc_U[:n_mo_act, sp]
                U_b_full = soc_U[n_mo_act:, sp]
                
                # Filter active components to match the evaluated C++ grid columns
                U_a_act = np.zeros(len(active_mos), dtype=complex)
                U_b_act = np.zeros(len(active_mos), dtype=complex)
                for p_rel in range(n_mo_act):
                    p_abs = offset + p_rel
                    if p_abs in mo_to_col:
                        U_a_act[mo_to_col[p_abs]] = U_a_full[p_rel]
                        U_b_act[mo_to_col[p_abs]] = U_b_full[p_rel]
                        
                psi_a = psi_chunk @ U_a_act
                psi_b = psi_chunk @ U_b_act
                rho_sp[sp][i : i+chunk_size] = np.abs(psi_a)**2 + np.abs(psi_b)**2
            
        # Build BSE Excitons (Density)
        psi_sq = psi_chunk**2
        for prefix in bse_states_dict:
            hw_act = bse_abs_holes[prefix][active_mos]
            ew_act = bse_abs_elecs[prefix][active_mos]
            rho_bse_h[prefix][i : i+chunk_size] = psi_sq @ hw_act
            rho_bse_e[prefix][i : i+chunk_size] = psi_sq @ ew_act
            
        if c_idx > 0 and c_idx % max(1, n_chunks // 10) == 0:
            print(f"    ... {(c_idx / n_chunks) * 100:4.1f}% complete in {time.time() - t0:.1f}s")

    origin_bohr = np.array([xs[0], ys[0], zs[0]]) * ANG_TO_BOHR
    spacing_bohr = spacing_ang * ANG_TO_BOHR

    # --- Label Generator Helper ---
    def get_lbl(idx, ref_idx, is_spinor=False):
        prefix = "sp" if is_spinor else "MO"
        if idx <= ref_idx:
            return f"{prefix}_HOMO" if idx == ref_idx else f"{prefix}_HOMO-{ref_idx - idx}"
        return f"{prefix}_LUMO" if idx == ref_idx + 1 else f"{prefix}_LUMO+{idx - ref_idx - 1}"

    # --- Write Files ---
    print("\n  [Cube] Exporting Cube Files...")
    
    for mo in mo_list:
        lbl = get_lbl(mo, solver.homo_index, False)
        write_cube(f"spatial_{lbl}.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx,Ny,Nz), rho_mo[mo], use_cpp)
        
    for sp in spinor_list:
        lbl = get_lbl(sp, solver.ham.n_occ_spinor - 1, True)
        write_cube(f"spinor_{lbl}_density.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx,Ny,Nz), rho_sp[sp], use_cpp)
        
    for prefix in bse_states_dict:
        write_cube(f"{prefix}_hole.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx,Ny,Nz), rho_bse_h[prefix], use_cpp)
        write_cube(f"{prefix}_elec.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx,Ny,Nz), rho_bse_e[prefix], use_cpp)


def generate_exciton_cubes(solver, bse_vec, shells, symbols, coords, prefix, spacing_ang=0.5, margin_ang=3.5, nthreads=4, use_cpp=True):
    """
    Evaluates MOs on a 3D grid in chunks to save memory, 
    and writes the resulting hole and electron densities to .cube files.
    """
    import libint_cpp
    ANG_TO_BOHR = 1.8897259886
    
    print(f"\n  [Cube] Initializing 3D Grid (spacing: {spacing_ang} Å, margin: {margin_ang} Å)...")
    mins = np.min(coords, axis=0) - margin_ang
    maxs = np.max(coords, axis=0) + margin_ang
    
    # Calculate number of grid points in each dimension
    Nx = int(np.ceil((maxs[0] - mins[0]) / spacing_ang))
    Ny = int(np.ceil((maxs[1] - mins[1]) / spacing_ang))
    Nz = int(np.ceil((maxs[2] - mins[2]) / spacing_ang))
    
    xs = np.linspace(mins[0], mins[0] + Nx*spacing_ang, Nx, endpoint=False)
    ys = np.linspace(mins[1], mins[1] + Ny*spacing_ang, Ny, endpoint=False)
    zs = np.linspace(mins[2], mins[2] + Nz*spacing_ang, Nz, endpoint=False)
    
    # Meshgrid 'ij' ensures coordinates align with cube file layout
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing='ij')
    grid_points_ang = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T
    grid_points_bohr = grid_points_ang * ANG_TO_BOHR
    n_points = len(grid_points_bohr)
    
    print(f"  [Cube] Grid size: {Nx} x {Ny} x {Nz} = {n_points} points.")
    
    # Pre-calculate MO weights for the exciton
    n_occ_tot = solver.C.shape[1] - solver.n_virt
    C_occ = solver.C[:, :n_occ_tot]
    C_virt = solver.C[:, n_occ_tot:]
    
    weights = bse_vec**2
    hole_weights = np.zeros(n_occ_tot)
    elec_weights = np.zeros(solver.n_virt)
    
    for idx, w in enumerate(weights):
        i_rel = solver.ham.valid_i[idx]
        a_rel = solver.ham.valid_a[idx]
        i_abs = (solver.homo_index - solver.n_occ + 1) + i_rel
        hole_weights[i_abs] += w
        elec_weights[a_rel] += w

    rho_h = np.zeros(n_points)
    rho_e = np.zeros(n_points)

    # -----------------------------------------------------------------
    # --- MASSIVE OPTIMIZATION: Filter out orbitals with zero weight --
    # -----------------------------------------------------------------
    threshold = 1e-6
    active_holes = np.where(hole_weights > threshold)[0]
    active_elecs = np.where(elec_weights > threshold)[0]
    
    C_occ_active = C_occ[:, active_holes]
    hole_weights_active = hole_weights[active_holes]
    
    C_virt_active = C_virt[:, active_elecs]
    elec_weights_active = elec_weights[active_elecs]
    
    print(f"  [Cube] Optimization: Reduced Hole MOs from {len(hole_weights)} to {len(active_holes)}")
    print(f"  [Cube] Optimization: Reduced Elec MOs from {len(elec_weights)} to {len(active_elecs)}")
    
    # NEW: Combine them so C++ only has to evaluate the Gaussians ONCE per chunk
    C_combined = np.ascontiguousarray(np.hstack([C_occ_active, C_virt_active]))
    n_active_holes = len(active_holes)
    # -----------------------------------------------------------------

    # CHUNK LOGIC: Prevent RAM explosion
    chunk_size = 10000 
    n_chunks = int(np.ceil(n_points / chunk_size))
    print(f"  [Cube] Evaluating grid in {n_chunks} chunks via C++ acceleration...")
    
    t0 = time.time()
    
    for c_idx, i in enumerate(range(0, n_points, chunk_size)):
        chunk_pts = grid_points_bohr[i : i+chunk_size]
        
        # ONE C++ call: Returns tiny (10000 x ~90) array instead of a massive (10000 x 15000) array
        psi_chunk = libint_cpp.evaluate_mos_on_grid(shells, C_combined, chunk_pts, nthreads)
        
        # Split the returned matrix back into holes and electrons
        psi_occ_chunk = psi_chunk[:, :n_active_holes]
        psi_virt_chunk = psi_chunk[:, n_active_holes:]
        
        # Final accumulation
        rho_h[i : i+chunk_size] = np.sum((psi_occ_chunk**2) * hole_weights_active, axis=1)
        rho_e[i : i+chunk_size] = np.sum((psi_virt_chunk**2) * elec_weights_active, axis=1)
        
        # Print a progress update every 10%
        if c_idx > 0 and c_idx % max(1, n_chunks // 10) == 0:
            elapsed = time.time() - t0
            pct = (c_idx / n_chunks) * 100
            print(f"    ... {pct:4.1f}% complete ({c_idx}/{n_chunks} chunks) in {elapsed:.1f}s")

    origin_bohr = np.array([xs[0], ys[0], zs[0]]) * ANG_TO_BOHR
    spacing_bohr = spacing_ang * ANG_TO_BOHR

    rho_diff = rho_e - rho_h
    
    print(f"  [Cube] Writing {prefix}_hole.cube ...")
    write_cube(f"{prefix}_hole.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx, Ny, Nz), rho_h, use_cpp=use_cpp)
    
    print(f"  [Cube] Writing {prefix}_elec.cube ...")
    write_cube(f"{prefix}_elec.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx, Ny, Nz), rho_e, use_cpp=use_cpp)

    # Write the combined difference file
    print(f"  [Cube] Writing {prefix}_diff.cube (Electron = Positive, Hole = Negative)...")
    write_cube(f"{prefix}_diff.cube", symbols, coords, origin_bohr, spacing_bohr, (Nx, Ny, Nz), rho_diff, use_cpp=use_cpp)

